- name: "Save Config"
  hosts: Cisco
  become: yes
  gather_facts: false

  tasks:
    - name: Show run
      ios_command:
        commands:
          - show run
      register: config

    - set_fact: time="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"

    - name: Save Output
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "data/config_{{ inventory_hostname }}{{ time }}.cfg"
